### ISSUE TITLE
Extend Should extensions for event log specifications

### ISSUE THREAD

**Issue by einari** [aksio-insurtech/Cratis#324]
For asserting specific event type with a value, rather than asserting the entire event:
`ShouldAppendEventWith<TEvent>(Func<TEvent, bool> callback)`

```csharp
[Fact] void should_append_my_event_with_correct_value () => event_log.ShouldAppendEventWith<MyEvent>(_ => _.MyValue == 42);
```

In addition for all should extensions, it would be nice to have an optional `Times` parameter that allows for asserting the number of expected appends. We could potentially use the `Moq` type for this, which already defines a rich way of doing this.

**Comment by Torgeir-Hansen** [comment]
There should be an override that also accepts Func<T, AppendedEventForSpecifications, bool> so that one can do matching on any relevant metadata as well.

**Comment by Torgeir-Hansen** [comment]
(and remember that the code with tests already exists internally in another aksio repo so it can probably be a lift
and shift😅)
