### ISSUE TITLE
Hard to figure out how to get going with a minimal setup

### ISSUE THREAD

**Issue by woksin** [aksio-insurtech/Cratis#943]
I just want to create a new dotnet project referencing the Cratis SDK and running Cratis in a minimal environment. However I cannot quickly deduce from the documentation or the Readme on how to setup that. 

What I would want is to be shown how to get a minimum project up and running. Easiest way to get from `dotnet new ...` to `dotnet run` and have a simple application running connected to Cratis that does nothing yet :)

- What nuget package to add
- What configuration is needed
- How to run Cratis sidecar (with a docker-compose would be nice)

**Comment by einari** [comment]
Just did a write up of this and it is at the time of writing this available [here](https://www.cratis.io/articles/get-started/basic.html).
